# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=3.4.2
FROM ghcr.io/rails/devcontainer/images/ruby:$RUBY_VERSION
# RUN apt-get update && apt-get install -y \
#     git \
#     curl \
#     sudo \
#     build-essential \
#     libssl-dev \
#     libffi-dev \
#     libpq-dev \
#     nodejs \
#     yarn \
#     postgresql-client \
#     tzdata \
    